eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8761/eureka/
#    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
server:
  port: 8762